In [4]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))  
from theODDS import p_helpers as p
from KALSHI import k_helpers as k 
import config

# Testing functions: 

Make a PoC file - no threading, run as simple as possible to show this is possible.

In [5]:
# sports = config.SPORTS

sports = ["basketball_nba"]

## Pinnacle Odds Fn

In [6]:
x = p.pinnacle_odds(sports, hrs = 70, live = False)
display(x)

,sport,event_id,home,away,commence,bookmaker,outcome,decimal_odds,implied_prob,vig_pct,fair_prob
0,basketball_nba,dce0f3f389617fa7daa990c209ee8acc,Atlanta Hawks,New York Knicks,2026-04-06 19:10:00-04:00,pinnacle,Atlanta Hawks,1.90,0.5263,2.383,0.5141
1,basketball_nba,dce0f3f389617fa7daa990c209ee8acc,Atlanta Hawks,New York Knicks,2026-04-06 19:10:00-04:00,pinnacle,New York Knicks,2.01,0.4975,2.383,0.4859
2,basketball_nba,ec27c42246b5e40c34f4c2d93930ed20,Orlando Magic,Detroit Pistons,2026-04-06 19:10:00-04:00,pinnacle,Detroit Pistons,1.68,0.5952,2.814,0.5789
3,basketball_nba,ec27c42246b5e40c34f4c2d93930ed20,Orlando Magic,Detroit Pistons,2026-04-06 19:10:00-04:00,pinnacle,Orlando Magic,2.31,0.4329,2.814,0.4211
4,basketball_nba,c2ff7eb921314ca5ebc2ad18db189374,Memphis Grizzlies,Cleveland Cavaliers,2026-04-06 20:10:00-04:00,pinnacle,Cleveland Cavaliers,1.09,0.9174,2.842,0.8921
5,basketball_nba,c2ff7eb921314ca5ebc2ad18db189374,Memphis Grizzlies,Cleveland Cavaliers,2026-04-06 20:10:00-04:00,pinnacle,Memphis Grizzlies,9.01,0.1110,2.842,0.1079
6,basketball_nba,14dede373d304abbddc590d2bcc81e4e,San Antonio Spurs,Philadelphia 76ers,2026-04-06 20:10:00-04:00,pinnacle,Philadelphia 76ers,3.96,0.2525,3.378,0.2443
7,basketball_nba,14dede373d304abbddc590d2bcc81e4e,San Antonio Spurs,Philadelphia 76ers,2026-04-06 20:10:00-04:00,pinnacle,San Antonio Spurs,1.28,0.7812,3.378,0.7557
8,basketball_nba,76e52ccb4140e4936de62dbadae0808d,Denver Nuggets,Portland Trail Blazers,2026-04-06 21:10:00-04:00,pinnacle,Denver Nuggets,1.31,0.7634,2.932,0.7416
9,basketball_nba,76e52ccb4140e4936de62dbadae0808d,Denver Nuggets,Portland Trail Blazers,2026-04-06 21:10:00-04:00,pinnacle,Portland Trail Blazers,3.76,0.2660,2.932,0.2584

## Kalshi Fn's

In [7]:
x2 = k.kalshi_odds(x)
display(x2)
# display(x2[x2['signal'] == True])

,sport,event_id,home,away,commence,outcome,fair_prob,k_event_ticker,k_ticker,yes_bid,yes_ask,no_bid,no_ask,volume,OI,match_score,signal
0,basketball_nba,14dede373d304abbddc590d2bcc81e4e,San Antonio Spurs,Philadelphia 76ers,2026-04-06 20:10:00-04:00,Philadelphia 76ers,0.2443,KXNBAGAME-26APR06PHISAS,KXNBAGAME-26APR06PHISAS-PHI,0.24,0.25,0.75,0.76,33883.00,32761.00,0.800,False
1,basketball_nba,14dede373d304abbddc590d2bcc81e4e,San Antonio Spurs,Philadelphia 76ers,2026-04-06 20:10:00-04:00,San Antonio Spurs,0.7557,KXNBAGAME-26APR06PHISAS,KXNBAGAME-26APR06PHISAS-SAS,0.76,0.77,0.23,0.24,261690.00,255982.00,0.786,False
2,basketball_nba,76e52ccb4140e4936de62dbadae0808d,Denver Nuggets,Portland Trail Blazers,2026-04-06 21:10:00-04:00,Denver Nuggets,0.7416,KXNBAGAME-26APR06PORDEN,KXNBAGAME-26APR06PORDEN-DEN,0.76,0.77,0.23,0.24,139584.00,139023.00,0.600,False
3,basketball_nba,c2ff7eb921314ca5ebc2ad18db189374,Memphis Grizzlies,Cleveland Cavaliers,2026-04-06 20:10:00-04:00,Cleveland Cavaliers,0.8921,KXNBAGAME-26APR06CLEMEM,KXNBAGAME-26APR06CLEMEM-CLE,0.91,0.92,0.08,0.09,76961.00,57717.00,0.643,False
4,basketball_nba,dce0f3f389617fa7daa990c209ee8acc,Atlanta Hawks,New York Knicks,2026-04-06 19:10:00-04:00,Atlanta Hawks,0.5141,KXNBAGAME-26APR06NYKATL,KXNBAGAME-26APR06NYKATL-ATL,0.52,0.53,0.47,0.48,212096.00,203742.00,0.700,False
5,basketball_nba,dce0f3f389617fa7daa990c209ee8acc,Atlanta Hawks,New York Knicks,2026-04-06 19:10:00-04:00,New York Knicks,0.4859,KXNBAGAME-26APR06NYKATL,KXNBAGAME-26APR06NYKATL-NYK,0.48,0.49,0.51,0.52,174856.00,158076.00,0.696,False
6,basketball_nba,ec27c42246b5e40c34f4c2d93930ed20,Orlando Magic,Detroit Pistons,2026-04-06 19:10:00-04:00,Detroit Pistons,0.5789,KXNBAGAME-26APR06DETORL,KXNBAGAME-26APR06DETORL-DET,0.58,0.59,0.41,0.42,253436.00,243259.00,0.636,False
7,basketball_nba,ec27c42246b5e40c34f4c2d93930ed20,Orlando Magic,Detroit Pistons,2026-04-06 19:10:00-04:00,Orlando Magic,0.4211,KXNBAGAME-26APR06DETORL,KXNBAGAME-26APR06DETORL-ORL,0.41,0.42,0.58,0.59,39983.00,31585.00,0.700,False